# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscategorybrand_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodImage',
            new_name='GoodsImage',
        ),
    ]
