# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_remove_goodsimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_sn',
            field=models.CharField(default='', max_length=50, verbose_name='商品唯一货号'),
        ),
    ]
