# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 01:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0009_hotsearchwords'),
        ('trade', '0003_auto_20180129_0003'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together=set([('user', 'goods')]),
        ),
    ]
