# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20180121_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavingmessage',
            name='message',
            field=models.TextField(default='messages/images/', help_text='留言内容', verbose_name='留言内容'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='subject',
            field=models.CharField(default='', max_length=100, verbose_name='主题'),
        ),
    ]
