# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 21:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_auto_20180128_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavingmessage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='文章時間', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(help_text='上传的文件', upload_to='message/images/', verbose_name='上传的文件'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='message',
            field=models.TextField(default='', help_text='留言内容', verbose_name='留言内容'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='subject',
            field=models.CharField(default='', help_text='文章主題', max_length=100, verbose_name='主题'),
        ),
    ]
